Repository tkurki/signalk-to-influxdb2, pull requests merged in 2023-11, with the labels that each got.

#35 Export navigation.position data in gpx format
  src/HistoryAPI.ts
  src/query.ts
Labels: feature

#36 Doc: update and extend history api docs and examples
  README.md
Labels: doc

#34 fix: create v1 db rp mapping on demand
  src/influx.ts
Labels: fix
